"""comment

Revision ID: 01cf29c512b8
Revises: 46333d0e620a
Create Date: 2018-05-01 11:19:47.299456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01cf29c512b8'
down_revision = '46333d0e620a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'disabled')
    # ### end Alembic commands ###
