"""fix

Revision ID: 46333d0e620a
Revises: ed13cfda0f6a
Create Date: 2018-04-30 23:06:54.823889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46333d0e620a'
down_revision = 'ed13cfda0f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operation_log_add_time', table_name='operation_log')
    op.drop_index('ix_operation_log_ip', table_name='operation_log')
    op.drop_table('operation_log')
    op.add_column('admin_log', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_log', 'info')
    op.create_table('operation_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('info', mysql.TEXT(), nullable=True),
    sa.Column('add_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='operation_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_operation_log_ip', 'operation_log', ['ip'], unique=False)
    op.create_index('ix_operation_log_add_time', 'operation_log', ['add_time'], unique=False)
    # ### end Alembic commands ###
