"""initial_video

Revision ID: 4dbffe66cccf
Revises: 8c4c5cd4dbd4
Create Date: 2018-04-06 00:00:18.471631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dbffe66cccf'
down_revision = '8c4c5cd4dbd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'video', 'user', ['uploader_id'], ['id'])
    op.drop_index('ix_video_collect_add_time', table_name='video_collect')
    op.drop_column('video_collect', 'id')
    op.drop_column('video_collect', 'add_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_collect', sa.Column('add_time', mysql.DATETIME(), nullable=True))
    op.add_column('video_collect', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.create_index('ix_video_collect_add_time', 'video_collect', ['add_time'], unique=False)
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.drop_column('video', 'uploader_id')
    # ### end Alembic commands ###
