"""like & log

Revision ID: 69b3373ee6e1
Revises: cf18842e9a46
Create Date: 2018-04-18 23:30:28.736727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69b3373ee6e1'
down_revision = 'cf18842e9a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('get_like_num', sa.BigInteger(), nullable=True))
    op.drop_column('user', 'thanks_num')
    op.drop_column('user', 'like_num')
    op.add_column('user_log', sa.Column('info', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_log_ip'), 'user_log', ['ip'], unique=False)
    op.drop_column('video', 'unlike')
    op.drop_column('video', 'thanks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thanks', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('unlike', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_log_ip'), table_name='user_log')
    op.drop_column('user_log', 'info')
    op.add_column('user', sa.Column('like_num', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('thanks_num', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('user', 'get_like_num')
    # ### end Alembic commands ###
