"""like

Revision ID: cf18842e9a46
Revises: 4054dc21f29b
Create Date: 2018-04-18 23:17:22.835014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf18842e9a46'
down_revision = '4054dc21f29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('like_num', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('thanks_num', sa.BigInteger(), nullable=True))
    op.add_column('video', sa.Column('like', sa.BigInteger(), nullable=True))
    op.add_column('video', sa.Column('thanks', sa.BigInteger(), nullable=True))
    op.add_column('video', sa.Column('unlike', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'unlike')
    op.drop_column('video', 'thanks')
    op.drop_column('video', 'like')
    op.drop_column('user', 'thanks_num')
    op.drop_column('user', 'like_num')
    # ### end Alembic commands ###
