"""thumbnail_cover

Revision ID: ed13cfda0f6a
Revises: f2dad65d8839
Create Date: 2018-04-30 00:09:07.930388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed13cfda0f6a'
down_revision = 'f2dad65d8839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail_cover', sa.Unicode(length=255), nullable=True))
    op.create_unique_constraint(None, 'video', ['thumbnail_cover'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_column('video', 'thumbnail_cover')
    # ### end Alembic commands ###
