"""like2

Revision ID: f2dad65d8839
Revises: 26fd16a11708
Create Date: 2018-04-22 11:16:54.692216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2dad65d8839'
down_revision = '26fd16a11708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('like', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
